extends Node

enum POLICIES {NONE = 0, IMT, BMT, SMT}
enum ARCHITECTURE{NONE = 0, SCALAR, SUPER}
enum EXECUTION_UNIT{NONE = 0, ALU, FPU, SIMD, DATA, CONTROL}
enum INSTRUCTIONS{STALL = 0, ADD, SUB, MUL, DIV, LW, SW, SLT, BEQ, BNE}
enum DEPENDENCIES{NONE=0, WAR, WAW, RAW}
