extends Node

enum PIPELINE_STAGES {IF = 0, ID, EX, MEM, WB}
enum POLICIES {NONE = 0, IMT, BMT, SMT, STD_SCALAR, STD_SUPERSCALAR}
enum ARCHITECTURE{NONE = 0, SCALAR, SUPER}
enum EXECUTION_UNIT{NONE = 0, ALU, FPU, SIMD, DATA, CONTROL}
enum INSTRUCTIONS{STALL = 0, ADD, SUB, MUL, DIV, LW, SW, SLT, BEQ, BNE}
enum DEPENDENCIES{NONE=0, WAR, WAW, RAW}
